Fix bug of diff vibrato mode
extract_smoothed_f0 assumes the input f0 to be of shape (T,), but
it was (T,1) that caused strange error

    raise ValueError("The length of the input vector x must be greater "
            ValueError: The length of the input vector x must be greater
            than padlen, which is 18.)